version: "3.8"

services:
#    php:
#        container_name: php
#        build:
#            context: ./..
#            dockerfile: php/Dockerfile1
#            args:
#                - PUID=${PUID}
#                - PGID=${PGID}
#                - INSTALL_XDEBUG=${INSTALL_XDEBUG}
#        environment:
#            PHP_IDE_CONFIG: "serverName=Docker"
#        volumes:
#            - /var/www/vendor/
#            - ./../:/var/www/
#        ports:
#            - ${NGINX_HOST_HTTP_PORT}:8080
#
    mysql:
        build:
            context: ./sql
        volumes:
            - db_data_mysql:/var/lib/minesql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            -  ${MYSQL_PORT}:3306
    postgres:
        image: postgres:16.3
        volumes:
            - db_data_postgres:/var/lib/postgres
        environment:
            POSTGRES_DB: ${PS_DB}
            POSTGRES_USER: ${PS_USER}
            POSTGRES_PASSWORD: ${PS_PASSWORD}
        ports:
            - ${PS_PORT1}:${PS_PORT2}
#    frontend:
#        container_name: frontend
#        build:
#            context: ./..
#            dockerfile: ./docker/frontend/Dockerfile
#        volumes:
#            - ./frontend:/app
#        ports:
#            - ${FRONTEND_PORT}:80
#        depends_on:
#            - php
volumes:
    db_data_postgres:
    db_data_mysql: